version: 2
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"